language: r

jobs:
  include:
  # Primary test
  - r: release
    os: linux
    after_success:
    - Rscript -e 'install.packages("covr"); covr::codecov()'
  # Secondary tests on merge
  - r: devel
    os: linux
    if: branch = master
  - r: release
    os: osx
    if: branch = master

matrix:
  fast_finish: true

cache: packages
warnings_are_errors: true
